version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    # Limit pull requests to 0 to only propose security updates
    open-pull-requests-limit: 1
    schedule:
      interval: "weekly"
    target-branch: "develop"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "develop"
