repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
        args: [--unsafe]
      - id: debug-statements
      - id: mixed-line-ending

  - repo: https://github.com/pycqa/doc8
    rev: v1.1.1
    hooks:
      - id: doc8
        entry: ./scripts/run_hook.py apps/rind python -m doc8
        exclude: ^(?!(apps/rind)).*$

  ## Python
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        types: [python]

  - repo: https://github.com/psf/black
    rev: 23.9.1
    hooks:
      - id: black
        types: [python]
