name: CD

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  get-package-version:
    name: Get ${{ github.ref_name }} package version
    runs-on: ubuntu-latest
    outputs:
      package-version: ${{ steps.package-version.outputs.package-version }}
      version-compairson: ${{ steps.semver.outputs.comparison-result}}
    steps:
      - name: Checkout ${{ github.repository }}
        uses: actions/checkout@v7

      - name: Install uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
        with:
          enable-cache: true

      - name: Setup Python
        run: uv python install

      - name: Get package version
        id: package-version
        run: echo "package-version=v$(uv version --short)" >> $GITHUB_OUTPUT

      - name: Get release version
        id: release-version
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          repository: ${{ github.repository }}

      - name: Analyze semver
        id: semver
        uses: madhead/semver-utils@latest
        with:
          lenient: false
          version: ${{ steps.package-version.outputs.package-version }}
          compare-to: ${{ steps.release-version.outputs.release }}

      - name: Check pre-release
        if: ${{ steps.semver.outputs.prerelease != '' }}
        run: |
          echo "Checking if version is a pre-release"
          echo "::error::Skipping pre-release version: ${{ steps.package-version.outputs.package-version}}"
          exit 1

  deploy:
    name: Deploy Python 🐍 distributions 📦 to PyPI
    needs: [get-package-version]
    runs-on: ubuntu-latest
    if: ${{ needs.get-package-version.outputs.version-compairson != '=' }}

    steps:
      - name: Checkout ${{ github.repository }}
        uses: actions/checkout@v7

      - name: Install uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
        with:
          enable-cache: true

      - name: Setup Python
        run: uv python install

      - name: Build and publish to PyPI
        run: uv publish --token ${{ secrets.PYPI_API_TOKEN }}

      - name: Create release ${{ needs.get-package-version.outputs.package-version }}
        uses: ncipollo/release-action@v1
        with:
          commit: ${{ github.ref_name }}
          tag: ${{ needs.get-package-version.outputs.package-version }}
          generateReleaseNotes: true
          artifacts: |
            dist/*.whl
            dist/*.tar.gz
