name: CI

on: [pull_request, workflow_dispatch, workflow_call]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"
          - "3.14"

    steps:
      - name: Checkout ${{ github.repository }}
        uses: actions/checkout@v7

      - name: Install uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
        with:
          enable-cache: true
          python-version: ${{ matrix.python-version }}

      - name: Setup Python ${{ matrix.python-version }}
        run: uv python install

      - name: Install dependencies
        id: uv-sync
        run: uv sync --locked --all-extras --dev

      - name: Run pre-commit
        run: uv run pre-commit run --all-files

      - name: Run Tests
        shell: bash
        run: |
          uv run pytest \
          --junitxml=pytest.xml \
          --cov-report=term-missing:skip-covered \
          --cov=welkin | tee pytest-coverage.txt

      - name: Add coverage comment
        uses: MishaKav/pytest-coverage-comment@main
        continue-on-error: true
        with:
          pytest-coverage-path: ./pytest-coverage.txt
          junitxml-path: ./pytest.xml
          report-only-changed-files: true
          title: Coverage Report (Python ${{ matrix.python-version }})
          unique-id-for-comment: ${{ matrix.python-version }}
          remove-link-from-badge: true
