name: Pre-commit auto-update

on:
  # every day at midnight
  schedule:
    - cron: "0 0 * * *"
  # on demand
  workflow_dispatch:

jobs:
  auto-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ${{ github.repository }}
        uses: actions/checkout@v7
        with:
          ref: develop

      - name: Install uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
        with:
          enable-cache: true

      - name: Setup Python
        run: uv python install

      - name: Install dependencies
        id: uv-sync
        run: uv sync --locked --all-extras --dev

      - name: Update pre-commit hooks
        run: uv run pre-commit autoupdate --color=always

      - name: Run pre-commit
        run: uv run pre-commit run --all-files
        continue-on-error: true

      - uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: update/pre-commit-hooks
          title: Update pre-commit hooks
          commit-message: "update pre-commit hooks"
          body: Update versions of pre-commit hooks to latest version.
